version: 0.2

env:
  variables:
    S3_BUCKET: "s3://jvictor-lab05"

phases:
  install:
    commands:
      - npm install -g npm@9
      - pip install --upgrade pip
      - pip install --upgrade awscli

  pre_build:
    commands:
      - npm install

  build:
    commands:
      - npm run build

  post_build:
    commands:
      - aws s3 cp build/ $S3_BUCKET --recursive
