version:0.2

env:
  variables:
    s3_bucket:"s3://jvictor-lab05"

phases:
  install:
    commands:
      - npm i npm@9 -g
      - pip install --upgrade pip
      - pip install --upgrade awscli

  pre_build:
    commands:
      - npm install

  build:
    commands:
      - npm run build

  post_build:
    commands:
      - aws s3 cp ./build $s3_bucket --recursive
